[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet restore",
  "dotnet publish -c Release -o out"
]

[phases.start]
cmd = "cd out && dotnet backLolaCredits.dll"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
