[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet restore backLolaCredits.csproj",
  "dotnet publish backLolaCredits.csproj -c Release -o out"
]

[start]
cmd = "dotnet out/backLolaCredits.dll"
