[build]
builder = "nixpacks"

[deploy]
startCommand = "dotnet backLolaCredits.dll"
healthcheckPath = "/api/dashboard/stats"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
